### ISSUE TITLE
gdal2 also fails to build

### ISSUE THREAD

**Issue by shaunstanislaus** [OSGeo/homebrew-osgeo4mac#270] opened 2017-09-06 07:27 UTC
```out
==> Downloading http://download.osgeo.org/gdal/2.2.1/gdal-2.2.1.tar.gz
Already downloaded: /Users/hackintosh/Library/Caches/Homebrew/gdal2-2.2.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/gdal2/2.2.1_2 --mandir=/usr/local/Cellar/gdal2/2.2.1_2/share/man --with-loc
==> make
Last 15 lines from /Users/hackintosh/Library/Logs/Homebrew/gdal2/02.make:
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitStuffer2.cpp  -fno-common -DPIC -o ../../o/.libs/BitStuffer2.o
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitMask2.cpp  -fno-common -DPIC -o ../../o/.libs/BitMask2.o
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port CntZImage.cpp  -fno-common -DPIC -o ../../o/.libs/CntZImage.o
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port RLE.cpp  -fno-common -DPIC -o ../../o/.libs/RLE.o
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitStuffer.cpp  -fno-common -DPIC -o ../../o/.libs/BitStuffer.o
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port Lerc2.cpp  -fno-common -DPIC -o ../../o/.libs/Lerc2.o
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitMask.cpp -o ../../o/BitMask.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port RLE.cpp -o ../../o/RLE.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitStuffer.cpp -o ../../o/BitStuffer.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitMask2.cpp -o ../../o/BitMask2.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port BitStuffer2.cpp -o ../../o/BitStuffer2.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port Lerc2.cpp -o ../../o/Lerc2.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port CntZImage.cpp -o ../../o/CntZImage.o >/dev/null 2>&1
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-32293-1tfa7zu/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port Huffman.cpp -o ../../o/Huffman.o >/dev/null 2>&1
make: *** [frmts-target] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/osgeo/homebrew-osgeo4mac/issues

These open issues may also help:
gdal2 fails to build https://github.com/OSGeo/homebrew-osgeo4mac/issues/269
gdal2 compilation failure https://github.com/OSGeo/homebrew-osgeo4mac/issues/257
Failed to build gdal2 with common flags https://github.com/OSGeo/homebrew-osgeo4mac/issues/245
brew install osgeo/osgeo4mac/gdal2-mrsid fails https://github.com/OSGeo/homebrew-osgeo4mac/issues/250
Using osgeo4mac's gdal2 with homebrew core's postgis https://github.com/OSGeo/homebrew-osgeo4mac/issues/185
gdal1-mrsid and gdal2-mrsid fails to build https://github.com/OSGeo/homebrew-osgeo4mac/issues/213
Linuxbrew support? https://github.com/OSGeo/homebrew-osgeo4mac/issues/225
error while Installing qgis-ltr in mac using terminal https://github.com/OSGeo/homebrew-osgeo4mac/issues/259
[WIP] Mongo support for gdal, help or review appreciated https://github.com/OSGeo/homebrew-osgeo4mac/pull/184
GRASS 7.2.0 failed to build https://github.com/OSGeo/homebrew-osgeo4mac/issues/208
Couldn't load SIP module. Python support will be disabled? https://github.com/OSGeo/homebrew-osgeo4mac/issues/223
Taudem failed to build; ld: unknown option: -headerpad_max_install_names; https://github.com/OSGeo/homebrew-osgeo4mac/issues/216
Move to homebrew-geospatial https://github.com/OSGeo/homebrew-osgeo4mac/issues/142
QGIS2 build fails in pyqt-qt4 make https://github.com/OSGeo/homebrew-osgeo4mac/issues/209
TauDEM Throwing Error After Good Install https://github.com/OSGeo/homebrew-osgeo4mac/issues/219
Monteverdi2 doesn't compile (Boost error) https://github.com/OSGeo/homebrew-osgeo4mac/issues/181
conflicting version recursive dependencies during upgrade https://github.com/OSGeo/homebrew-osgeo4mac/issues/265
QGIS2 - could not load "processing" plugin https://github.com/OSGeo/homebrew-osgeo4mac/issues/203

```

**Comment by pat-s** [comment] 2017-09-06 13:00
same here

```ruby
==> Downloading http://download.osgeo.org/gdal/2.2.1/gdal-2.2.1.tar.gz
Already downloaded: /Users/pjs/Library/Caches/Homebrew/gdal2-2.2.1.tar.gz
==> ./configure --prefix=/usr/local/Cellar/gdal2/2.2.1_2 --mandir=/usr/local/Cellar/gdal2/2.2.1_2/share/man --with-local=/usr/local/Cellar/gdal2/2.2.1_2 --with-threads --with-libtool --with-pcraster=internal --with-pcidsk=internal --with-bsb --with-grib --with-pam --wit
==> make

[...]
libtool: compile:  clang++ -std=gnu++11 -arch x86_64 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough -DGNM_ENABLED -I/usr/local/Cellar/gdal2/2.2.1_2/include -I/private/tmp/gdal2-20170906-26307-1wnglz9/gdal-2.2.1/port -I/usr/local/opt/armadillo/include -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/Cellar/netcdf/4.4.1.1_6/include -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr/local -I/usr/local/include -I/usr -I/usr/include -DGDAL_COMPILATION -c -I../../port Lerc2.cpp -o ../../o/Lerc2.o >/dev/null 2>&1
make: *** [frmts-target] Error 2
```

**Comment by shaunstanislaus** [comment] 2017-09-06 17:00
@pat-s any idea what's wrong with it?

**Comment by ateucher** [comment] 2017-09-07 00:28
I'm getting the same error, though it looks at a different point. Full logs here: https://gist.github.com/ateucher/d441735895b4207bc413005ce2383052

**Comment by dakcarto** [comment] 2017-09-07 15:33
Closing as duplicate of #269.

Please note, when doing multi-core compilations, any final error is generally not the actual error that caused the build to fail. When posting log output from a multi-core build, that last error notice is _usually_ preceded by completely unrelated output from other parallel jobs that are finishing up first, with the actual error much further up in the log.

The best way to find the actual in-line error in the log is go to `~/Library/Logs/Homebrew/<formula>/0#.make` (for Make builds) and search for **`Error:`** (with colon).

Unfortunately, the `brew gist-logs` command can truncate large log files before uploading, indicated by a `[...snip...]` in the uploaded log. In which case, the in-source error may have been removed; so searching `~/Library/Logs/Homebrew/<formula>/<log>` is the only way to find the actual error.

When reporting issues, post the actual error and the matching compilation command preceding it, or update the output of `brew gist-logs` with the full log file that was truncated.

**Closed by dakcarto** 2017-09-07 15:33 UTC
