### ISSUE TITLE
Can't install qgis2.18.10 -- make failure

### ISSUE THREAD

**Issue by renkeji** [OSGeo/homebrew-osgeo4mac#256] opened 2017-08-10 00:12 UTC
```
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang
-- Check for working C compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++
-- Check for working CXX compiler: /usr/local/Homebrew/Library/Homebrew/shims/super/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- QGIS version: 2.18.10 Las Palmas (21810)
-- Looking for openpty
-- Looking for openpty - found
-- Found Proj: /usr/local/lib/libproj.dylib
-- Found GEOS: /usr/local/Cellar/geos/3.6.2/lib/libgeos_c.dylib (3.6.2)
-- Found GDAL: /usr/local/opt/gdal2/lib/libgdal.dylib (2.2.1)
-- Found Expat: /usr/local/opt/expat/lib/libexpat.dylib
-- Found Spatialindex: /usr/local/lib/libspatialindex.dylib
-- Found Qwt: /usr/local/opt/qwt-qt4/lib/qwt.framework/qwt (6.1.3)
-- Found Sqlite3: /usr/local/opt/sqlite/lib/libsqlite3.dylib
-- Found PostgreSQL: /usr/local/lib/libpq.dylib
-- Found SpatiaLite: /usr/local/lib/libspatialite.dylib
-- Looking for gaiaDropTable in /usr/local/lib/libspatialite.dylib
-- Looking for gaiaDropTable in /usr/local/lib/libspatialite.dylib - found
-- Looking for gaiaStatisticsInvalidate in /usr/local/lib/libspatialite.dylib
-- Looking for gaiaStatisticsInvalidate in /usr/local/lib/libspatialite.dylib - found
-- Looking for spatialite_init_ex in /usr/local/lib/libspatialite.dylib
-- Looking for spatialite_init_ex in /usr/local/lib/libspatialite.dylib - found
-- Qt WebKit support enabled
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - found
-- Looking for QT_MAC_USE_COCOA
-- Looking for QT_MAC_USE_COCOA - found
-- Found Qt4: /usr/local/opt/qt-4/bin/qmake (found suitable version "4.8.7", minimum required is "4.8.0")
-- Found Qt version: 4.8.7
-- Touch support disabled
CMake Error at cmake/FindQScintilla.cmake:65 (FILE):
  FILE failed to open for reading (No such file or directory):
```

**Comment by luisspuerto** [comment] 2017-08-10 22:35
I can't make qgis also

**Comment by dakcarto** [comment] 2017-08-11 02:23
Hi @renkeji, thanks for reporting!

Closing as duplicate of #255. Please follow that report, which also has full [Troubleshooting](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md) logs.

**Closed by dakcarto** 2017-08-11 02:23 UTC
