### ISSUE TITLE
gdal-20 not building under Mac OS 10.10.5

### ISSUE THREAD

**Issue by katossky** [OSGeo/homebrew-osgeo4mac#139] opened 2016-05-16 02:05 UTC
I am desperately trying to install QGIS on my machine, with no success.

Running `brew install qgis-214` fails when building `gdal-20` at the make step, without error.

I need guidance to know what is important to specify to resolve the bug - if there is one.

**Comment by katossky** [comment] 2016-05-16 02:44
`qgis-28` was correctly installed.

**Comment by katossky** [comment] 2016-05-16 03:03
... but `processing` is not installed (installation fails with `pip`) and `psychopg2` is not found (even though installation with `pip` completed). That said, QGIS seems to work.

**Comment by holstius** [comment] 2016-05-16 17:12
Same problem here. `brew install osgeo/osgeo4mac/gdal` fails mysteriously with `osgeo/osgeo4mac/gdal-20 2.0.2 did not build`. Same failure with `brew install gdal --HEAD`.

Last lines of `config.log` are:

```
#define HAVE_5ARGS_MREMAP 1
#define HAVE_SC_PHYS_PAGES 1
#define HAVE_ICONV 1
#define ICONV_CONST 
#define ICONV_CPP_CONST 
#define HAVE_SQLITE3_H 1
#define HAVE_PCRE_H 1
#define GDAL_PREFIX "/usr/local/Cellar/gdal-20/2.0.2"

configure: exit 0
```

**Comment by dakcarto** [comment] 2016-05-16 20:27
@katossky, thanks for reporting! Please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md) logs

**Comment by dakcarto** [comment] 2016-05-16 20:34
@katossky wrote:
> ... but processing is not installed (installation fails with pip) and psychopg2 is not found (even though installation with pip completed). That said, QGIS seems to work.

'Processing' is not a Python module, it is a core PyQGIS plugin inside of QGIS. Doing `pip install processing` will not work. If Processing is failing at QGIS startup due to missing psycopg2, it will need to be installed.

If using Homebrew's `python`, then doing `<homebrew-prefix>/bin/pip install psycopg2` will remedy the issue, just as noted in the `brew info qgis-214` notes. Check those notes to see if there are other modules that you need to install.

**Comment by dakcarto** [comment] 2016-05-16 20:41
@holstius, thanks for reporting! Please provide [Troubleshooting](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md) logs

Please note that this issue is about `osgeo/osgeo4mac/gdal-20`, not `osgeo/osgeo4mac/gdal` (non-existent) or `gdal` (Homebrew GDAL 1.11.x), which are different formulae.

**Comment by katossky** [comment] 2016-05-16 20:44
https://gist.github.com/anonymous/b1bb31053ff0e4504d0e0392328e2e0b

**Comment by katossky** [comment] 2016-05-16 20:49
Hum...

   /usr/local/bin/pip install --upgrade psycopg2

gives:

   Requirement already up-to-date: psycopg2 in /usr/local/lib/python3.5/site-packages

**Comment by katossky** [comment] 2016-05-16 20:53
If it is related, `rgdal` in `R` refuses to read `GPX` files. It seems like it may come from a build of `gdal` without the `expat` library (source: http://r-sig-geo.2731867.n2.nabble.com/reading-gpx-using-readOGR-td6612044.html) even thoufh `gdal` and `expat` are already installed via brew...

**Comment by dakcarto** [comment] 2016-05-16 21:26
@katossky, the build error is:
```
cpl_vsisimple.cpp:959:30: error: use of undeclared identifier '_SC_PHYS_PAGES'
    return ((GIntBig)sysconf(_SC_PHYS_PAGES)) * sysconf(_SC_PAGESIZE);
                             ^
1 error generated.
make[1]: *** [cpl_vsisimple.lo] Error 1
make: *** [port-target] Error 2
make: *** Waiting for unfinished jobs....
```

Which is a bit odd since previously, in configure, it states:
```
checking for _SC_PHYS_PAGES... yes
```
which maybe 10.10 doesn't support (it says the same for 10.11, but compiles fine).

Though the source has an optional [RAM query for APPLE](https://github.com/OSGeo/gdal/blob/2.0/gdal/port/cpl_vsisimple.cpp#L962-L979), it is being skipped in your build.

My guess is that you have some header being pulled in during these compilation lines:

```
/bin/sh /private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/libtool --mode=compile --tag=CXX clang++ -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/port -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/gcore -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/alg -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/ogr -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/ogr/ogrsf_frmts -arch x86_64 -g -O2  -Wall  -DOGR_ENABLED -I/usr/local/Cellar/gdal-20/2.0.2/include -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/port -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr -I/usr/include  -DGDAL_COMPILATION	  -DHAVE_CURL -DHAVE_LIBZ -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2 -DHAVE_LIBXML2 -c -o cpl_vsisimple.lo cpl_vsisimple.cpp
libtool: compile:  clang++ -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/port -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/gcore -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/alg -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/ogr -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/ogr/ogrsf_frmts -arch x86_64 -g -O2 -Wall -DOGR_ENABLED -I/usr/local/Cellar/gdal-20/2.0.2/include -I/private/tmp/gdal-20-20160516-78991-zhvzqn/gdal-2.0.2/port -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/local/opt/libpng/include -I/usr -I/usr/include -DGDAL_COMPILATION -DHAVE_CURL -DHAVE_LIBZ -I/usr/local/Cellar/libxml2/2.9.3/include/libxml2 -DHAVE_LIBXML2 -c cpl_vsisimple.cpp  -fno-common -DPIC -o .libs/cpl_vsisimple.o
```

Though I don't see anything odd there.

It checks for the support [here in configure](https://github.com/OSGeo/gdal/blob/2.0/gdal/configure.in#L587-L605). So, I'm guessing you have an unsupported `unistd.h` that is being referenced _later on_ in the build, or 10.10 is incorrectly stating the actual support.

Your `brew doctor` output doesn't look so good. May be causing issues.

**Comment by katossky** [comment] 2016-05-16 22:04
Thank you so much for helping reading my log fil! But I must admit I do not know what's the next thing I should try... Any idea?

I started reacting to the warnings issued by `brew doctor` but I am not sure if I really must comply with all warnings. For instance:

     Warning: Unbrewed dylibs were found in /usr/local/lib.
     If you didn't put them there on purpose they could cause problems when
     building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
      /usr/local/lib/libtcl8.6.dylib
      /usr/local/lib/libtk8.6.dylib

... seems to be related to a `R` package (source: http://stackoverflow.com/questions/25212800/error-onload-failed-in-loadnamespace-for-tcltk). Should I then reinstall `R` with `brew`?

**Comment by holstius** [comment] 2016-05-17 15:51
I updated from 10.10 to 10.11 overnight. Will post soon re: whether that resolves the issue.

**Comment by holstius** [comment] 2016-05-17 17:05
Updating to OS X 10.11.5 and Xcode 7.2.1 (7C1002) solved it for me. The only warning I get is:

```
Warning: osgeo/osgeo4mac/gdal-20 dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```

**Comment by dakcarto** [comment] 2016-05-17 18:01
@holstius wrote:
> Updating to OS X 10.11.5 and Xcode 7.2.1 (7C1002) solved it for me. The only warning I get is:
> 
>  `Warning: osgeo/osgeo4mac/gdal-20 dependency gcc was built with a different C++ standard`
>  `library (libstdc++ from clang). This may cause problems at runtime.`

Yeah, that is for the `gcc` formula that is pulled in for `gfortran` used by the locally built `numpy`. [I have an issue filed](https://github.com/Homebrew/homebrew-python/issues/301) on that and [we are working on eliminating that direct `gcc` dependency](https://github.com/OSGeo/homebrew-osgeo4mac/pull/140).

`gdal-20` is built using clang (libc++), whereas gcc (libstdc++) is obviously not. You can safely ignore that warning. See also [C++ Standard Libraries](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/C%2B%2B-Standard-Libraries.md).

**Comment by rkrug** [comment] 2016-05-24 10:15
Hm. I have just upgraded to OS X 10.11.5 and have Xcode 7.3.1 (7D1014) and I can not compile gdal-20.

here is my debug [gist](https://gist.github.com/rkrug/770bfa99c6ab12abfd87dae0313ff906)

**Comment by rkrug** [comment] 2016-05-27 09:20
Any news on this bug? I still can't install gdal-20 (see my previous gist)

**Comment by dakcarto** [comment] 2016-06-06 01:45
This thread is for Mac OS 10.10.5. If you have issues compiling on another OS/compiler setup, please submit a new ticket. (btw, @rkrug, I don't actually see an error in your logs.)

Closing this comment thread as it is thoroughly polluted with different issues now.

**Closed by dakcarto** 2016-06-06 01:45 UTC

**Comment by bbradbury** [comment] 2016-10-07 17:33
I dropped into the brew shell via `brew install gdal2 --debug`, and ran `VERBOSE=1 make`

libtool: compile:  clang++ -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/port -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/gcore -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/a
lg -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/ogr -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/ogr/ogrsf_frmts -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/gnm -I/private/t
mp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/apps -arch x86_64 -g -O2 -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror
=vla -Wnull-dereference -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -DOGR_ENABLED -I/usr/local/Cellar/gdal2/2.1.1/include
 -I/private/tmp/gdal2-20161007-18443-1oebhhc/gdal-2.1.1/port -I/usr/local -I/usr/local/include -I/usr/local -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/libpng -I/usr/lo
cal/opt/libpng/include -I/usr -I/usr/include -DGDAL_COMPILATION -DHAVE_CURL -DHAVE_LIBZ -I/usr/local/Cellar/libxml2/2.9.4/include/libxml2 -DHAVE_LIBXML2 -DUSE_ONLY_CRYPTODLL_ALG -c cpl_sha256.cpp -o cpl_s
ha256.o >/dev/null 2>&1
**cpl_vsisimple.cpp:1120:41: error: use of undeclared identifier '_SC_PHYS_PAGES'
    return static_cast<GIntBig>(sysconf(_SC_PHYS_PAGES))**

**Comment by bbradbury** [comment] 2016-10-07 17:58
_SC_PHYS_PAGES error occurs when the unistd.h that gdal sees when configuring differes from the one used when compiling. Related discussion here: https://github.com/Homebrew/legacy-homebrew/issues/47026#issuecomment-197925412

**Comment by bbradbury** [comment] 2016-10-07 18:12
Success: `brew install osgeo/osgeo4mac/gdal2 --env=std`

**Comment by luipir** [comment] 2016-10-24 18:20
@bbradbury confirmed on 10.10.5, thank you for the solution
