### ISSUE TITLE
Newly renamed qgis formula bottle is missing

### ISSUE THREAD

**Issue by jonathanmccormack** [OSGeo/homebrew-osgeo4mac#615] opened 2019-01-22 14:46 UTC
When I went to install the newly renamed "qgis" formula (for QGIS 3.4.4), I received the following error:
```
==> Installing osgeo/osgeo4mac/qgis
==> Downloading https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qgis-3.4.4.mojave.bottle.3.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "qgis"
Download failed: https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qgis-3.4.4.mojave.bottle.3.tar.gz
Warning: Bottle installation failed: building from source.
```
Browsing bintray, I see there exists a bottle for qgis: [qgis-3.4.4.mojave.bottle.1.tar.gz](https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/:qgis-3.4.4.mojave.bottle.1.tar.gz) but no bottle named "qgis-3.4.4.mojave.bottle.3.tar.gz".  While it looks like the bottle build succeeded on Travis, the upload to bintray [did not](https://travis-ci.com/OSGeo/homebrew-osgeo4mac/builds/98095861#L6830):
```
Deploying application
[Bintray Upload] Reading descriptor file: travis/bintray-upload.json
[Bintray Upload] Uploading file 'bottles/qgis-3.4.4.high_sierra.bottle.3.tar.gz' to qgis-3.4.4.high_sierra.bottle.3.tar.gz
[Bintray Upload] Bintray response: 403 Forbidden. Account resource usage limits were met for 'homebrew-osgeo'
[Bintray Upload] Uploading file 'bottles/qgis-3.4.4.high_sierra.bottle.json' to qgis-3.4.4.high_sierra.bottle.json
[Bintray Upload] Bintray response: 403 Forbidden. Account resource usage limits were met for 'homebrew-osgeo'
[Bintray Upload] Uploading file 'bottles/qgis-3.4.4.mojave.bottle.3.tar.gz' to qgis-3.4.4.mojave.bottle.3.tar.gz
[Bintray Upload] Bintray response: 403 Forbidden. Account resource usage limits were met for 'homebrew-osgeo'
[Bintray Upload] Uploading file 'bottles/qgis-3.4.4.mojave.bottle.json' to qgis-3.4.4.mojave.bottle.json
[Bintray Upload] Bintray response: 403 Forbidden. Account resource usage limits were met for 'homebrew-osgeo'
[Bintray Upload] Uploading file 'bottles/qgis-3.4.4.sierra.bottle.3.tar.gz' to qgis-3.4.4.sierra.bottle.3.tar.gz
[Bintray Upload] Bintray response: 403 Forbidden. Account resource usage limits were met for 'homebrew-osgeo'
[Bintray Upload] Uploading file 'bottles/qgis-3.4.4.sierra.bottle.json' to qgis-3.4.4.sierra.bottle.json
[Bintray Upload] Bintray response: 403 Forbidden. Account resource usage limits were met for 'homebrew-osgeo'
[Bintray Upload] Publishing version '0.1' of package 'bottles'...
[Bintray Upload] Bintray response: 200 OK.
```
Looks like the bintray account is out of space.  Presumably some of the older bottles for deleted / renamed formulas could be deleted (e.g., [qgis3-3.2.1.sierra.bottle.tar.gz](https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/:qgis3-3.2.1.sierra.bottle.tar.gz)).

Relatedly, as a suggestion, can the deploy script be modified to verify that the bintray upload actually was successful?  Receiving a 403 response when uploading shouldn't provide a successful build status to Travis.

**Comment by juanfrans** [comment] 2019-01-22 17:40
Same problem here. I get the same error message:
`==> Installing qgis from osgeo/osgeo4mac
==> Downloading https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qgis-3.4.4.mojave.bottle.3.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "qgis"
Download failed: https://dl.bintray.com/homebrew-osgeo/osgeo-bottles/qgis-3.4.4.mojave.bottle.3.tar.gz
Warning: Bottle installation failed: building from source.`

After that the installation stalls at:
`==> /usr/local/Cellar/qgis/3.4.4/libexec/vendor/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/qgis--numpy-20190122-44665-imq69n/numpy-1.15.4
==> cmake -G Ninja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qgis/3.4.4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMA
==> cmake --build . --target all -- -j 12`

**Comment by fjperini** [comment] 2019-01-22 18:01
@jonathanmccormack I will try to solve this!

@juanfrans given the new LTR (3.4.x), we have renamed `qgis2` to `qgis-ltr@2.18`

**Comment by fjperini** [comment] 2019-01-22 18:16
@nickrobison You can take care of removing bottles that are no longer necessary.

**Comment by nickrobison** [comment] 2019-01-23 20:20
@fjperini I believe the issue is due to the amount of traffic on the repo, not simply the amount of space being used. I can try to clear out some of the bottles, but I’m not sure that will help.

**Comment by fjperini** [comment] 2019-01-25 02:44
@nickrobison did you manage to check this?

**Comment by fjperini** [comment] 2019-01-27 06:13
We'll have to wait for Bintray to review what happens with the problem we're having. @nickrobison gave notice.

An alternative that works is to publish the builds in GitHub Release (requires a Token).

**Comment by garrettdashnelson** [comment] 2019-01-31 23:41
Nothing useful to add other than I've discovered the same problem with the most recent bottles. I _was_ able to install the older 3.4.4 bottle (via bintray) using the previously committed formula.

**Comment by fjperini** [comment] 2019-02-05 21:09
@nickrobison News? Given the problems with bintray, it would be good to temporarily generate a Token to publish the bottles in the Release section.

**Comment by fjperini** [comment] 2019-02-11 22:48
I have solved this! 🎉

**Comment by fjperini** [comment] 2019-02-11 23:00
In the course of the day I will go rebuilding the bottles.

**Comment by juanfrans** [comment] 2019-02-12 15:01
@fjperini Thank you. Looking forward to installing it.

**Closed** 2019-02-12 16:57 UTC
