### ISSUE TITLE
GDAL 2.2.2 fails to build

### ISSUE THREAD

**Issue by pat-s** [OSGeo/homebrew-osgeo4mac#277] opened 2017-09-28 21:22 UTC
macOS Sierra
XCode 9.0

02.Make:
```
In file included from /private/tmp/gdal2-20170928-41495-1dpacm6/gdal-2.2.2/port/cpl_port.h:659:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: error: no member named 'signbit' in the global namespace
using ::signbit;
      ~~^
```

Gist logs: https://gist.github.com/5bdb0fe13879dcb2dd46ac899d47e045

**Comment by dd-a** [comment] 2017-10-03 13:48
Same here. (macOS Sierra, XCode 9.0)

**Comment by jerr0328** [comment] 2017-10-04 10:21
See #276

**Comment by dakcarto** [comment] 2017-10-18 23:59
Closing as duplicate of #276. Reopen if necessary.

**Closed by dakcarto** 2017-10-18 23:59 UTC
